package xrayconfig

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/base64"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"strings"
	"time"

	"golang.org/x/crypto/curve25519"
)

// AutoProvisionProtocol describes one inbound created (or already present)
// as part of an auto-provisioning run.
type AutoProvisionProtocol struct {
	Protocol string `json:"protocol"`
	Tag      string `json:"tag"`
	Port     int    `json:"port"`
	Created  bool   `json:"created"`
}

// AutoProvisionResult is the outcome of AutoProvisionBestProtocols.
type AutoProvisionResult struct {
	Protocols []AutoProvisionProtocol `json:"protocols"`
}

type autoProvisionSpec struct {
	protocol string
	tag      string
	build    func(tag string, port int, catalog Catalog, usedDests map[string]bool) (map[string]any, error)
}

func autoProvisionSpecs() []autoProvisionSpec {
	return []autoProvisionSpec{
		{protocol: "vless", tag: "auto-vless-reality", build: buildAutoVLESSReality},
		{protocol: "trojan", tag: "auto-trojan-reality", build: buildAutoTrojanReality},
		{protocol: "hysteria", tag: "auto-hysteria2", build: buildAutoHysteria2},
		{protocol: "shadowsocks", tag: "auto-shadowsocks", build: buildAutoShadowsocks},
	}
}

// AutoProvisionTags lists the inbound tags AutoProvisionBestProtocols owns,
// in the order they are provisioned.
func AutoProvisionTags() []string {
	specs := autoProvisionSpecs()
	tags := make([]string, 0, len(specs))
	for _, spec := range specs {
		tags = append(tags, spec.tag)
	}
	return tags
}

// AutoProvisionBestProtocols creates a curated set of modern, well-hardened
// Xray inbounds on the master node — VLESS+REALITY, Trojan+REALITY (backup),
// Hysteria2, and Shadowsocks — each getting its own auto-created host row
// exactly like a manually created inbound would (ensureInboundRecordTx). An
// admin only needs to create a user afterward; per-protocol client
// credentials are generated by the existing user-creation flow.
//
// Re-running it is a no-op for any protocol whose tag already exists, so
// clicking the button again is safe and just reports the existing setup.
func (r Repository) AutoProvisionBestProtocols(ctx context.Context) (AutoProvisionResult, error) {
	config, err := r.readMasterConfigForPlanning(ctx)
	if err != nil {
		return AutoProvisionResult{}, err
	}
	used, ranges := extractUsedPorts(config)
	catalog := r.loadCatalog(ctx)
	usedDests := map[string]bool{}

	result := AutoProvisionResult{}
	for _, spec := range autoProvisionSpecs() {
		existing, err := r.GetInbound(ctx, spec.tag)
		if err != nil && !errors.Is(err, ErrInboundNotFound) {
			return AutoProvisionResult{}, err
		}
		if existing != nil {
			port, _ := parseConfigPort(existing["port"])
			result.Protocols = append(result.Protocols, AutoProvisionProtocol{
				Protocol: spec.protocol, Tag: spec.tag, Port: port, Created: false,
			})
			continue
		}

		port, err := pickAvailablePortFrom(used, ranges)
		if err != nil {
			return AutoProvisionResult{}, err
		}
		used[port] = true

		payload, err := spec.build(spec.tag, port, catalog, usedDests)
		if err != nil {
			return AutoProvisionResult{}, fmt.Errorf("%s: %w", spec.protocol, err)
		}
		if _, err := r.CreateInbound(ctx, payload); err != nil {
			return AutoProvisionResult{}, fmt.Errorf("%s: %w", spec.protocol, err)
		}
		result.Protocols = append(result.Protocols, AutoProvisionProtocol{
			Protocol: spec.protocol, Tag: spec.tag, Port: port, Created: true,
		})
	}
	return result, nil
}

func (r Repository) readMasterConfigForPlanning(ctx context.Context) (map[string]any, error) {
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer rollbackQuietly(tx)
	return r.masterRawConfigTx(ctx, tx)
}

func pickAvailablePortFrom(used map[int]bool, ranges []portRange) (int, error) {
	for i := 0; i < 200; i++ {
		candidate, err := randomPort(autoInboundMinPort, autoInboundMaxPort)
		if err != nil {
			break
		}
		if !isPortUsed(candidate, used, ranges) {
			return candidate, nil
		}
	}
	for candidate := autoInboundMinPort; candidate <= autoInboundMaxPort; candidate++ {
		if !isPortUsed(candidate, used, ranges) {
			return candidate, nil
		}
	}
	return 0, ErrNoAvailablePort
}

func buildAutoVLESSReality(tag string, port int, catalog Catalog, usedDests map[string]bool) (map[string]any, error) {
	privateKey, _, err := generateRealityKeyPair()
	if err != nil {
		return nil, err
	}
	shortID, err := generateRealityShortIDHex()
	if err != nil {
		return nil, err
	}
	option := pickRealityDest(catalog.RealityPool, usedDests)
	usedDests[option.Dest] = true
	return map[string]any{
		"tag":      tag,
		"listen":   "::",
		"port":     port,
		"protocol": "vless",
		"settings": map[string]any{
			"clients":    []any{},
			"decryption": "none",
		},
		"streamSettings": map[string]any{
			"network":  "tcp",
			"security": "reality",
			"realitySettings": map[string]any{
				"show":        false,
				"dest":        option.Dest,
				"xver":        0,
				"serverNames": stringsToAny(option.ServerNames),
				"privateKey":  privateKey,
				"shortIds":    []any{shortID},
			},
		},
	}, nil
}

func buildAutoTrojanReality(tag string, port int, catalog Catalog, usedDests map[string]bool) (map[string]any, error) {
	privateKey, _, err := generateRealityKeyPair()
	if err != nil {
		return nil, err
	}
	shortID, err := generateRealityShortIDHex()
	if err != nil {
		return nil, err
	}
	option := pickRealityDest(catalog.RealityPool, usedDests)
	usedDests[option.Dest] = true
	return map[string]any{
		"tag":      tag,
		"listen":   "::",
		"port":     port,
		"protocol": "trojan",
		"settings": map[string]any{
			"clients": []any{},
		},
		"streamSettings": map[string]any{
			"network":  "tcp",
			"security": "reality",
			"realitySettings": map[string]any{
				"show":        false,
				"dest":        option.Dest,
				"xver":        0,
				"serverNames": stringsToAny(option.ServerNames),
				"privateKey":  privateKey,
				"shortIds":    []any{shortID},
			},
		},
	}, nil
}

func stringsToAny(values []string) []any {
	out := make([]any, len(values))
	for i, value := range values {
		out[i] = value
	}
	return out
}

func buildAutoHysteria2(tag string, port int, _ Catalog, _ map[string]bool) (map[string]any, error) {
	certLines, keyLines, err := generateSelfSignedCertLines("next-hysteria2")
	if err != nil {
		return nil, err
	}
	return map[string]any{
		"tag":      tag,
		"listen":   "::",
		"port":     port,
		"protocol": "hysteria",
		"settings": map[string]any{
			"clients": []any{},
		},
		"streamSettings": map[string]any{
			"tlsSettings": map[string]any{
				"alpn": []any{"h3"},
				"certificates": []any{
					map[string]any{
						"certificate": certLines,
						"key":         keyLines,
					},
				},
			},
		},
	}, nil
}

func buildAutoShadowsocks(tag string, port int, _ Catalog, _ map[string]bool) (map[string]any, error) {
	return map[string]any{
		"tag":      tag,
		"listen":   "::",
		"port":     port,
		"protocol": "shadowsocks",
		"settings": map[string]any{
			"clients": []any{},
			"network": "tcp,udp",
		},
	}, nil
}

func generateRealityKeyPair() (privateKey string, publicKey string, err error) {
	priv := make([]byte, curve25519.ScalarSize)
	if _, err = rand.Read(priv); err != nil {
		return "", "", err
	}
	pub, err := curve25519.X25519(priv, curve25519.Basepoint)
	if err != nil {
		return "", "", err
	}
	return base64.RawURLEncoding.EncodeToString(priv), base64.RawURLEncoding.EncodeToString(pub), nil
}

func generateRealityShortIDHex() (string, error) {
	value := make([]byte, 4)
	if _, err := rand.Read(value); err != nil {
		return "", err
	}
	return hex.EncodeToString(value), nil
}

// generateSelfSignedCertLines creates a fresh self-signed leaf certificate so
// protocols that require TLS (Hysteria2) work immediately from just a server
// IP, with no real domain/CA involved. Clients connect with certificate
// verification disabled for this host, same as any self-signed TLS setup.
func generateSelfSignedCertLines(commonName string) ([]string, []string, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, err
	}
	now := time.Now().UTC()
	template := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: commonName},
		NotBefore:             now.Add(-time.Hour),
		NotAfter:              now.Add(10 * 365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return nil, nil, err
	}
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyBytes, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, nil, err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyBytes})
	return splitPEMLines(string(certPEM)), splitPEMLines(string(keyPEM)), nil
}

func splitPEMLines(value string) []string {
	trimmed := strings.TrimRight(value, "\n")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "\n")
}
